version: '3'
services:
  app:
    build:  
      context: ./app
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "5000:5000"
    networks:
      - bridge
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db_container
    ports:
      - "3306:3306"
    networks:
      - bridge
networks:
  bridge:
    driver: bridge

